services:

    plant-api:
        build:
          context: .
        command:
            - /bin/sh
            - -c
            - |
                echo "wait for 5 seconds"
                sleep 5
                uvicorn src.run:application --host 0.0.0.0 --port 2310 --reload --timeout-keep-alive 1000
        volumes:
            - .:/src/app
        env_file:
            - src/.env
        logging:
          options:
            max-size: 10m
        deploy:
          resources:
            reservations:
              memory: 20M
        depends_on:
          - db_plant
        ports:
            - 2310:2310

    db_plant:
        restart: always
        image: postgres:15.3
        container_name: db_plant
        env_file:
            - src/.env
        volumes:
            - postgres_data:/var/lib/postgresql/data/
        ports:
            - 8080:8080
        logging:
          driver: none

    plant_adminer_db:
        container_name: plant_adminer_db
        image: adminer
        restart: always
        depends_on:
            - db_plant
        ports:
            - 8110:8080

volumes:
    postgres_data:
