class_names = [
    'Apple___Apple_scab', 'Apple___Black_rot', 'Apple___Cedar_apple_rust', 'Apple___healthy',
    'Blueberry___healthy', 'Cherry_(including_sour)___Powdery_mildew', 'Cherry_(including_sour)___healthy',
    'Corn_(maize)___Cercospora_leaf_spot Gray_leaf_spot', 'Corn_(maize)___Common_rust_', 'Corn_(maize)___Northern_Leaf_Blight',
    'Corn_(maize)___healthy', 'Grape___Black_rot', 'Grape___Esca_(Black_Measles)', 'Grape___Leaf_blight_(Isariopsis_Leaf_Spot)',
    'Grape___healthy', 'Orange___Haunglongbing_(Citrus_greening)', 'Peach___Bacterial_spot', 'Peach___healthy',
    'Pepper,_bell___Bacterial_spot', 'Pepper,_bell___healthy', 'Potato___Early_blight', 'Potato___Late_blight',
    'Potato___healthy', 'Raspberry___healthy', 'Soybean___healthy', 'Squash___Powdery_mildew', 'Strawberry___Leaf_scorch',
    'Strawberry___healthy', 'Tomato___Bacterial_spot', 'Tomato___Early_blight', 'Tomato___Late_blight', 'Tomato___Leaf_Mold',
    'Tomato___Septoria_leaf_spot', 'Tomato___Spider_mites Two-spotted_spider_mite', 'Tomato___Target_Spot',
    'Tomato___Tomato_Yellow_Leaf_Curl_Virus', 'Tomato___Tomato_mosaic_virus', 'Tomato___healthy'
]

class_labels_ru = {
    'Apple___Apple_scab': "Яблоня — парша",
    'Apple___Black_rot': "Яблоня — чёрная гниль",
    'Apple___Cedar_apple_rust': "Яблоня — решётчатая ржавчина яблони",
    'Apple___healthy': "Яблоня — здоровое растение",
    'Blueberry___healthy': "Голубика — здоровое растение",
    'Cherry_(including_sour)___Powdery_mildew': "Вишня — мучнистая роса",
    'Cherry_(including_sour)___healthy': "Вишня — здоровое растение",
    'Corn_(maize)___Cercospora_leaf_spot Gray_leaf_spot': "Кукуруза — церкоспороз",
    'Corn_(maize)___Common_rust_': "Кукуруза — ржавчина кукурузы",
    'Corn_(maize)___Northern_Leaf_Blight': "Кукуруза — гельминтоспориоз листьев, пятнистость гельминтоспориозная",
    'Corn_(maize)___healthy': "Кукуруза — здоровое растение",
    'Grape___Black_rot': "Виноград — чёрная гниль",
    'Grape___Esca_(Black_Measles)': "Виноград — чёрная корь",
    'Grape___Leaf_blight_(Isariopsis_Leaf_Spot)': "Виноград — пятнистость листьев",
    'Grape___healthy': "Виноград — здоровое растение",
    'Orange___Haunglongbing_(Citrus_greening)': "Апельсин — Хуанлунбин (Грининг цитрусовых)",
    'Peach___Bacterial_spot': "Персик — бактериальная пятнистость",
    'Peach___healthy': "Персик — здоровое растение",
    'Pepper,_bell___Bacterial_spot': "Перец сладкий — бактериальная пятнистость",
    'Pepper,_bell___healthy': "Перец сладкий — здоровое растение",
    'Potato___Early_blight': "Картофель — альтернариоз",
    'Potato___Late_blight': "Картофель — фитофтороз",
    'Potato___healthy': "Картофель — здоровое растение",
    'Raspberry___healthy': "Малина — здоровое растение",
    'Soybean___healthy': "Соя — здоровое растение",
    'Squash___Powdery_mildew': "Кабачок — мучнистая роса",
    'Strawberry___Leaf_scorch': "Клубника — ожог листьев",
    'Strawberry___healthy': "Клубника — здоровое растение",
    'Tomato___Bacterial_spot': "Томат — бактериальная пятнистость",
    'Tomato___Early_blight': "Томат — альтернариоз",
    'Tomato___Late_blight': "Томат — фитофтороз",
    'Tomato___Leaf_Mold': "Томат — кладоспориоз",
    'Tomato___Septoria_leaf_spot': "Томат — септориоз",
    'Tomato___Spider_mites Two-spotted_spider_mite': "Томат — паутинный клещ",
    'Tomato___Target_Spot': "Томат — мишеневидная пятнистость",
    'Tomato___Tomato_Yellow_Leaf_Curl_Virus': "Томат — вирус жёлтого скручивания листьев томата",
    'Tomato___Tomato_mosaic_virus': "Томат — вирус мозаики",
    'Tomato___healthy': "Томат — здоровое растение",
}
